name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Before creating a new feature request, please search existing issues to make sure a similar feature hasn't already been suggested.

  - type: textarea
    id: problem
    attributes:
      label: "❓ Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is"
      placeholder: "I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "💡 Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "🤔 Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "ℹ️ Additional context"
      description: "Add any other context, screenshots, or examples about the feature request here"
    validations:
      required: false
